### ISSUE TITLE
有一些疑问

### ISSUE THREAD

**Issue by February3O** [Steve245270533/gallery#3]
你好。
在core/index.ts有这段代码
  this.ui = new UI();
在ui/index.ts中
  this.core = new Core();
这样是否会形成循环依赖呢？

**Comment by Steve245270533** [comment]
你说的对，这样的模式会形成循环依赖，也破坏了最小知识原则，因为主要是我觉得如果在各处都通过传很多参数也很麻烦，不知道各位有没有更好的设计方法，我们可以一起讨论一下

**Comment by guoxq971** [comment]
他不是用的的单例模式；
这样应该还会循环依赖吗；

**Comment by Steve245270533** [comment]
> 他不是用的的单例模式； 这样应该还会循环依赖吗；

首先需要明白为什么采用单例模式，因为在开发的时候我想的是只会创建一个WebGL实例用于展馆应用，其他的各个类都是基于`Core`这个类提供的WebGL上下文来进一步开发。因此在各个功能类中执行`this.core = new Core()`的时候，由于`Core`类中做了单例模式，因此拿到的core实例对象都是同一个，所以在后续开发中都是在同一个WebGL上下文操作。

这样做的好处就是非常方便，在开发其它功能类中，直接在其它类中声明一个core实例，之后就可以直接使用core实例上面的数据，但是这样会产生循环依赖，因为core中实例化了ui类，但是ui类中又包含了一个core实例，因此`this.core.ui.core.ui.core.ui.core.xxx`可以无限地引用下去。

但也并不是说循环依赖就一定是有问题的，只是在开发大型项目的时候由于这种情况导致的业务耦合问题非常不利于排错和业务梳理，其中一个方案就是采用`依赖注入`的方式解决，这个可以参考我后续的[character-simulator](https://github.com/Steve245270533/character-simulator)这个项目中的开发模式。

原本我想的是也把`gallery`这个项目也改成`character-simulator`项目那样，后来想想算了，这两个项目的开发风格正好可以给大家对比参考一下。如果又需要改的，大家就参考[character-simulator](https://github.com/Steve245270533/character-simulator)这个项目改就行了。

希望这个回答能帮助到你。
