### ISSUE TITLE
M1 mac 无法移动位置和视角

### ISSUE THREAD

**Issue by IndigoMagic** [Steve245270533/gallery#5]
在M1Mac上成功启动了项目，控制台没有报错
浏览器的控制台也没有明显报错
但是用触摸板无法移动视角和位置
<img width="1290" alt="image" src="https://github.com/Steve245270533/gallery/assets/37242294/d0f9ec38-da77-47c3-9b92-d8b87b08ba94">

**Comment by bcd-github** [comment]
我也是M1的 我用wasd可以移动

**Comment by IndigoMagic** [comment]
我试了一下，确实可以移动，但是好像还是没有按键可以调节视角

**Comment by Steve245270533** [comment]
`w`/`a`/`s`/`d`是控制移动的，移动视角需要鼠标拖动，可能需要鼠标操作方便一些，我后期把操作说明写md文档上

**Comment by IndigoMagic** [comment]
如果后续有优化，希望可以增加对触摸板事件的识别❤️💕
经常出差携带鼠标有点不便🤣
