### ISSUE TITLE
鼠标点击地面移动

### ISSUE THREAD

**Issue by ha0z1819** [Steve245270533/gallery#6]
1.如果可以用鼠标点击地面就自己走过去在某些场景会不会更方便一些

2.可以在页面的右上角加一个帮助按钮---帮助刚进来的人了解怎么操作

3.如果场景大了的话可以在固定地点加个位置，在底部加个预览栏，点击就可以跳转过去

**Comment by Steve245270533** [comment]
**非常感谢您的支持和宝贵意见🌹🌹🌹**

关于您提出的第一点，如果要实现这个交互，那么`物理引擎`和`碰撞检测`就显得没有必要了，可以直接使用`NavMesh导航`的方式，主要起初就是为了能使展馆操作自由度更高一些才仿照游戏里的第一人称视角结合碰撞检测做的，PC端键盘加鼠标控制，移动端使用摇杆。所以关于第一条建议一定程度上会更适用于全景贴图VR展馆，或者第三人称固定视角下的交互。

**帮助按钮**和**快速导航至指定地点**是非常符合本项目的功能需求，后续有时间我会陆续加上，非常感谢🥰！！！

**Comment by shenqidweisuo** [comment]
你好 我通过threejs加载你的模型scene_collision.glb，发现地板和栏杆是黑色的，用three.js editor打开这个模型也是黑色的，只有把环境设置成modelviewer才能显示出来，请问该怎么在代码里现实modelviewer的功能啊

**Comment by Steve245270533** [comment]
> 你好 我通过threejs加载你的模型scene_collision.glb，发现地板和栏杆是黑色的，用three.js editor打开这个模型也是黑色的，只有把环境设置成modelviewer才能显示出来，请问该怎么在代码里现实modelviewer的功能啊

scene_collision.glb中的有一些模型是PBR材质的，比起基础的Material材质，需要在场景中加入光源才能显示，在新版本three中，点光源的intensity属性貌似需要调大一些才有效果。
